### ISSUE TITLE
Tracking issue: Client package updates

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1194]
Improvements to the interface of the client package to better support external integrations:

- [x] https://github.com/penumbra-zone/nextjs-penumbra-client-example/issues/1
- [x] https://github.com/penumbra-zone/nextjs-penumbra-client-example/issues/2
- [x] https://github.com/penumbra-zone/web/issues/1093
- [x] https://github.com/penumbra-zone/web/issues/1193
- [x] https://github.com/penumbra-zone/web/issues/1192
- [x] https://github.com/penumbra-zone/web/issues/825
- [x] Update `penumbra-zone/nextjs-penumbra-client-example` to support latest client package
- [x] https://github.com/penumbra-zone/web/issues/1190
