### ISSUE TITLE
Tracking Issue: Client Sync Mechanism

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1376]
Improve the performance of the web client sync and block processor mechanism to mitigate the slow syncing that'll be experienced by chain state bloat.

- [x] https://github.com/penumbra-zone/web/issues/1576
- [x] https://github.com/penumbra-zone/web/issues/1278
- [x] https://github.com/penumbra-zone/penumbra/issues/1131
- [x] https://github.com/penumbra-zone/web/issues/1428
- [x] https://github.com/penumbra-zone/web/issues/1377
- [x] https://github.com/penumbra-zone/web/issues/1378 and https://github.com/penumbra-zone/web/issues/1495 
- [x] https://github.com/penumbra-zone/web/issues/1496
- [x] https://github.com/prax-wallet/web/issues/161
