### ISSUE TITLE
Send dialog should allow specifying a source account / planning should use sources

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#161]
Currently, the Send dialog doesn't allow specifying a source account. I'm also not sure whether the planning is actually scoped by account, as it should be, but in any case the UI blocks it.

Here's the state of my balances:
<img width="764" alt="Screen Shot 2023-10-28 at 1 15 14 PM" src="https://github.com/penumbra-zone/web/assets/44879/8b6939da-81d9-4128-a27a-d44d3876e309">
The dialog says I only have 8 gm available, the balance in account 0. When I try to send 1000gm, I get:
<img width="413" alt="Screen Shot 2023-10-28 at 1 15 00 PM" src="https://github.com/penumbra-zone/web/assets/44879/dc7016c0-501a-4b90-899b-41e9b2f2850b">

I think a good UI here would be to have a picker for "Source" above the "Recipient" box, so that the user first selects the source account (or accepts the default selection, the UI could be slightly different so that it's de-emphasized as an "input", like the picker in the popup:

<img width="388" alt="Screen Shot 2023-10-28 at 1 19 55 PM" src="https://github.com/penumbra-zone/web/assets/44879/275bcafa-8e0e-4284-85eb-8e61ef25831e">

We should also check that the extension's implementation of the `TransactionPlanner` respects source control.

**Comment by hdevalence** [comment]
From the point of view of the frontend, I think that all that has to happen here is setting the source field of the TransactionPlannerRequest. If the wasm view server doesn't respect it, that's a bug that can be fixed independently.

**Comment by Valentine1898** [comment]
I've split this issue into three different ones 
- [ ] https://github.com/penumbra-zone/penumbra/issues/3333 - add source control support to wasm planner 
- [ ] https://github.com/penumbra-zone/web/issues/243 - TransactionPlannerRequest handler must consider source
- [ ] https://github.com/penumbra-zone/web/issues/244 - User should be able to choose the account from which he is going to spend funds when sending (UI issue)

**Comment by Valentine1898** [comment]
Closed as done after  https://github.com/penumbra-zone/web/pull/266 merged
