### ISSUE TITLE
Tracking issue: v2 of minifront UI

### ISSUE THREAD

**Issue by VanishMax** [penumbra-zone/web#1710]
Everything related to the v2 release of minifront UI.

This tracking issue is moved from https://github.com/prax-wallet/web/issues/81 since it is better to keep in the place of actual implementation.

Required for v2:
- [x] https://github.com/prax-wallet/web/issues/82
- [x] https://github.com/prax-wallet/web/issues/83
- [x] https://github.com/prax-wallet/web/issues/84
- [x] https://github.com/prax-wallet/web/issues/113
- [x] https://github.com/prax-wallet/web/issues/114
- [x] https://github.com/prax-wallet/web/issues/115
- [x] https://github.com/prax-wallet/web/issues/156
- [x] https://github.com/prax-wallet/web/issues/142
- [x] https://github.com/prax-wallet/web/issues/151
- [x] https://github.com/prax-wallet/web/issues/155
- [x] https://github.com/prax-wallet/web/issues/137
- [x] https://github.com/prax-wallet/web/issues/160
- [x] #1713
- [x] https://github.com/penumbra-zone/web/issues/1730
- [x] https://github.com/penumbra-zone/web/issues/1731
- [x] https://github.com/penumbra-zone/web/issues/1732
- [x] #1715
- [x] #1714
- [x] #1743
- [x] #1744
- [x] #1745
- [x] #1776
- [x] #1773
- [x] #1774
- [ ] #1781
- [x] #1756
- [ ] v2: Shield page
- [ ] v2: Unshield page
- [ ] v2: Swap page
- [ ] v2: Staking page
- [x] #1754
- [x] #1778

Bugs and additional non-blocking features:
- [ ] https://github.com/prax-wallet/web/issues/131
- [ ] https://github.com/prax-wallet/web/issues/132
- [ ] https://github.com/prax-wallet/web/issues/147

Technical: 
- [x] #1703 
- [x] https://github.com/prax-wallet/web/issues/158
- [x] https://github.com/prax-wallet/web/issues/157
- [ ] https://github.com/prax-wallet/web/issues/162
- [ ] https://github.com/prax-wallet/web/issues/119

**Comment by TalDerei** [comment]
tagging some other UI issues as relevant scope
- https://github.com/penumbra-zone/web/issues/1120
- https://github.com/penumbra-zone/web/issues/1171
- https://github.com/penumbra-zone/web/issues/1238
- https://github.com/penumbra-zone/web/issues/1302 and https://github.com/penumbra-zone/web/pull/1734#pullrequestreview-2267839802
- https://github.com/penumbra-zone/web/issues/1589

**Comment by TalDerei** [comment]
tagging https://github.com/penumbra-zone/web/issues/432 as relevant

**Comment by TalDerei** [comment]
we have two V2 tracking issues — should we consolidate the relevant tasks into https://github.com/penumbra-zone/web/issues/1937 and close this one in favor of the more recent issue? cc @VanishMax

**Comment by VanishMax** [comment]
Closed non-relevant issues and moved all relevant to #1937
