### ISSUE TITLE
Tracking Issue: Refactor Service Worker Lifecycle 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1790]
the motivation is detailed in https://github.com/penumbra-zone/web/issues/1573 (tracked in https://github.com/penumbra-zone/web/issues/1376). The necessary work from that issue has been compartmentalized into smaller, distinct work streams. It's a large lift that necessitates extensive testing. 

reference the accompanying architectural design document: https://docs.google.com/document/d/1QqP3OfW4Rqa1awYJdTDD9ao8nV8vHDYM4IJjapraHYA/edit

-----------------------------------------------------------------------------------------------------------------------------------

**Phase 1**

1. [x] https://github.com/penumbra-zone/web/issues/1573

-----------------------------------------------------------------------------------------------------------------------------------

**Phase 2**

2. [x] https://github.com/penumbra-zone/web/issues/1787
3. [x] https://github.com/penumbra-zone/web/issues/1809

-----------------------------------------------------------------------------------------------------------------------------------

**Phase 3**

5. [x] https://github.com/penumbra-zone/web/issues/924
6. [x] https://github.com/penumbra-zone/web/issues/1789

-----------------------------------------------------------------------------------------------------------------------------------

**Potential Low Hanging Fruit**

7. [x] https://github.com/penumbra-zone/web/issues/1814

**Comment by TalDerei** [comment]
update: I'll probably close this tracking issue and associated sub-issues in favor of directing efforts to improving the syncing algorithm itself – we should generally avoid making extensive architectural refactors.
