### ISSUE TITLE
UIv2 Library Designs — Tracking List

### ISSUE THREAD

**Issue by smmhrdmn** [penumbra-zone/web#1937]
**Is your feature request related to a problem? Please describe.**
New ui designs need to be implemented so minifront can be updated and others can utilize the library.

**Describe the solution you'd like**
Call the current state of the UIv2 Library done, and begin implementing changes. This tracking list can be used to mark off components that have been **_fully implemented_** into the ui library. As components are implemented or issues are created from here, please make note of them here. 

**Describe alternatives you've considered**
n/a

**Additional context**

- [UIv2 Library designs](https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?m=auto&node-id=1600-80188&t=10ultq3wW4cPHe3R-1)
- Further details on what changes have been made to each component are outlined in Figma. Some of these changes are minor and some are major. If you have any questions about changes, or run into any issues, please reach out.

### Primitives _(ready for dev)_

- [ ] Color _(alternative black added)_
- [ ] Icon _(a few miscellaneous icons added that are not Lucide icons)_

### Semantics _(ready for dev)_

- [ ] Color _(Several color additions, including gradients)_
- [ ] Typography _(additional text styles added based on DEX designs)_

### Components _(ready for dev)_

- [ ] Account selector
- [ ] Action Views — _(new component)_
- [ ] Address view
- [ ] Alert — _(new component)_
- [x] Asset Icon — _(no changes)_
- [ ] Asset Group — _(new component)_
- [ ] Asset Selector
- [ ] Asset Value Input 
- [ ] Auction Routing
- [ ] Block sync bar
- [ ] Block sync popover
- [ ] Button
- [ ] Button group
- [ ] Card base — _(previously Card)_
- [ ] Dialog
- [ ] Input field — _(major changes)_
- [ ] Icon
- [ ] Icon Adornment
- [x] Identicon — _(no changes)_
- [ ] List item — _(major changes)_
- [ ] Menu item
- [ ] Pill
- [ ] Popover
- [ ] Segmented control
- [ ] Slider
- [ ] Swap asset selector — _(new component)_
- [ ] Swap Claim — _(new component)_
- [ ] Swap Value Input 
- [ ] Swap routing
- [ ] Navigation bar
- [ ] Tab
- [ ] Table cell — _(previously Table)_
- [ ] Toast — _(new component)_
- [x] Toggle — _(no changes)_
- [ ] Tooltip
- [ ] Value View — _(major changes)_
- [ ] Wallet balance
- [ ] Transaction Summary — _(new component)_

### Pages _(wrapping up)_

- [ ] Portfolio
- [ ] Shielding — _(ready for dev)_
- [ ] Transfer — _(ready for dev)_
- [ ] Swap
- [ ] Stake

**Comment by VanishMax** [comment]
PR https://github.com/penumbra-zone/web/pull/1939 checks these items: Color, Button

**Comment by TalDerei** [comment]
PR https://github.com/penumbra-zone/web/pull/1941: `Address View` component

**Comment by grod220** [comment]
Let's put the PRs in line with the checklist item 🙏

**Comment by hdevalence** [comment]
Can we break down the action views into a list with sub-items? There are a fair number of them so would be useful to track separately.

**Comment by hdevalence** [comment]
They need to be implemented as components, but the ones that don't have designs could be something as simple as

> Action Name
> (!) Unimplemented Action

The important thing is to have all the components there so that, e.g., the tx view can render the list of actions correctly

**Comment by VanishMax** [comment]
Linking the still-relevant issues from #1710 

- [ ] #1781
- [ ] https://github.com/prax-wallet/web/issues/131
- [ ] https://github.com/prax-wallet/web/issues/132
- [ ] https://github.com/prax-wallet/web/issues/147
- [ ] https://github.com/penumbra-zone/web/issues/1171

**Comment by smmhrdmn** [comment]
Has the transaction summary component been implemented? xref  https://github.com/penumbra-zone/penumbra/issues/4939

**Comment by VanishMax** [comment]
@smmhrdmn no, we didn't touch this part yet. 

This tracking list constantly updates, so you can trust the checkbox not being set next to 'transaction summary component' :)
