### ISSUE TITLE
Tracking issue: User can view balances

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#24]
- [ ] Service worker can download compact block range and store data in indexdb + zustand
- [ ] Dapp can request balances from extension (view server in extension)
- [ ] Extension only handles messages from dapps that users have specifically "connected" to

- [ ] Explore how to use web-workers inside service workers
  - [ ] Using web-workers directly. **Update**: Not supported.
  - [ ] Using wasm-threads (wasm-rayon-bindgen). **Update**: Not possible as it uses workers underneath the hood.
  - [ ] Using offscreen api. **Update**: Solution works. However, doesn't look like comlink works via this method.
  - [ ] Document these learnings in the repo.
- [ ] Explore indexdb versus sqlite wasm (newly available)
