### ISSUE TITLE
Tracking issue: Penumbra-web pages/components

### ISSUE THREAD

**Issue by zpoken** [penumbra-zone/web#25]
_**Overall Goal**_:  The parts of the UI (pages/components/etc) that still need migrating to the new repo

Extension pages:

- [x] Welcome
- [x] Import Seed Phrase
   - [x] Set Password 
- [x] Generate New Seed Phrase
   - [x] Confirm Seed Phrase
   - [x] Set Password 
- [x] Success Create Account
- [x] Login
- [x] Restore Password
    - [x] Set Password 
- [x] Main
- [x] Settings
    - [x] Advanced. Feature :
         - [x] Auto-lock timer
         - [x] Clear cache
    - [x] Security & Privacy. Feature :
         - [x] Show recovery passphrase
         - [x] Show full viewing key
         - [x] Show spend key
    - [x] Network. Feature :
         - [x] Select network
         - [x] Change grpc url
    - [x] Permissions. Feature ???

Dapp pages:

- [ ] Balances
    - [ ] Show balance
    - [ ] Send tx
    - [ ] transaction history
- [ ] Swap

**Comment by grod220** [comment]
We should include the dapp elements as well
