### ISSUE TITLE
Tracking issue: Web client sync

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#31]
**Overall Goal**: Fully migrate client sync functionality in `penumbra-zone/wallet` to `penumbra-zone/web`

- [x] Controllers: https://github.com/penumbra-zone/web/pull/28
  - [x] IndexedDb class
  - [x] WasmViewServer class
  - [x] BlockProcessor class
  - [x] Obvious client
  - [x] Specific client
- [ ] `checkLastNctRoot` debug method to verify tree validity
- [ ] Abort controller to handle:
  - Wallet reset
  - Sync errors (should restart)
- [ ] Graceful retries and time backoffs (5 second retry, then 30 second, then...)
- [ ] Store notes
- [ ] Update stored notes that have been spent
- [ ] Store assetId -> denom map
- [ ] Store transaction
- [ ] Store LP nft
- [ ] Store swaps
- [ ] Store fmd parameters
- [ ] Store SCT: commitments, hashes, position, forgotten 
- [ ] Service worker initializes background services (with controllers inside)
   - On install (or connect?) should look for active wallet and begin sync automatically
   - On emitted event from popup (after completed onboarding flow), begin sync
- [ ] Validate success via manual testing/balances query
