### ISSUE TITLE
Tracking issue: grpc service tests

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#333]
Objective: substantially add test coverage to our view & custody service tests.

### View service
- [x] Add tests for BalancesRequest
- [x] Add tests for NotesRequest
- [x] Add tests for NullifierStatusRequest
- [x] #397
- [x] #398
- [x] #400
- [x] #401
- [x] #402
- [x] #403
- [x] #409
- [x] #405
- [x] #404
- [x] #407
- [x] #399
- [x] #406
- [x] #506
- [x] #408
- [x] #411
- [x] #535
- [x] #536
- [x] #538
- [x] #539
- [x] #537
- [x] #410
- [x] #412

### Custody service
- [x] #413
- [x] #414

**Comment by grod220** [comment]
Likely many of these tests should be blocked by #312

**Comment by grod220** [comment]
Well done @Valentine1898!
