### ISSUE TITLE
Tracking Issue: IBC support

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#343]
We want an end-to-end flow of users being able to IBC in and out of Penumbra seamlessly. 

Excalidraw context: https://excalidraw.com/#room=fb6162dcb92b741806e2,hWaSBNlMI557IG5y0I1A7g

- [x] https://github.com/penumbra-zone/web/pull/270
- [x] https://github.com/penumbra-zone/web/issues/132
- [x] https://github.com/penumbra-zone/web/pull/269
- [x] https://github.com/cosmos/ibc-proto-rs/issues/165
- [x] https://github.com/penumbra-zone/web/issues/248
- [x] https://github.com/penumbra-zone/web/issues/800
- [x] https://github.com/penumbra-zone/web/issues/812
- [x] https://github.com/penumbra-zone/web/issues/703
- [x] https://github.com/penumbra-zone/web/pull/982
- [x] https://github.com/penumbra-zone/web/pull/1014
- [x] https://github.com/penumbra-zone/web/issues/79
- [x] https://github.com/penumbra-zone/web/issues/1052
- [x] https://github.com/penumbra-zone/web/issues/1049
- [x] https://github.com/penumbra-zone/web/issues/1053
- [x] https://github.com/penumbra-zone/web/issues/1050
- [x] https://github.com/penumbra-zone/web/issues/1051
- [ ] #344
- [ ] #1188

**Comment by TalDerei** [comment]
pruning the backlog, what's the current status of this tracking issue?

**Comment by grod220** [comment]
Those last two issues are still relevant, but the spirit of this epic is completed
