### ISSUE TITLE
Tracking issue: Swap

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#389]
Implement the DEX part of our DEX...

- [x] https://github.com/penumbra-zone/web/issues/390
- [x] #420
  - claim should not require auth (should either be handled by web app or automatically by view service)
- [x] #468
- [x] #423
- [x] #467 
- [x] #473
- [x] #421
- [x] https://github.com/penumbra-zone/web/issues/532
- [x] #566
- [x] #548
- [x] https://github.com/penumbra-zone/web/issues/735
- [x] #424
- [x] https://github.com/penumbra-zone/web/issues/533
- [x] https://github.com/penumbra-zone/web/issues/1069
- [x] #560
- [x] #422 (deprioritized for now, per @hdevalence)
