### ISSUE TITLE
Tracking issue: Penumbra-web foundations

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#4]
**_Overall Goal_**: Begin the first step of the [vision outlined in the wallet repo](https://github.com/penumbra-zone/wallet/issues/16). Focused on setting up the new repo (with all the new type safety checks) & migrating account setup code (refactoring alongside).

Breakdown:
- [x] Create new repo `penumbra/web` with TurboRepo boilerplate: [NEW REPO](https://github.com/penumbra-zone/web)
  - [x] Strictest `.tsconfig` config
  - [x] Eslint rules
  - [x] Prettier
- [x] Github actions for PRs. Should run tests, lints & builds. https://github.com/penumbra-zone/web/pull/1
  - [x] https://github.com/penumbra-zone/web/pull/6 
- [x] Apps directory
   - [x] Web app starter
   - [x] Extension starter https://github.com/penumbra-zone/web/pull/3
- [x] Package directory
  - [x] UI
- [x] Integrate tailwind (TailwindMerge/clsx) + radix-ui + shadcn/ui 
  - [x] https://github.com/penumbra-zone/web/pull/2
  - [x] #7 
- [x] Integrate state management w/ local/session persistence
  - [x] #7 
  - [x] #10 
- [x] Testing
   - [x] Unit testing: https://github.com/penumbra-zone/web/pull/15
   - [x] Component snapshot testing (Edit: decided against this for now. Should consider visual regression testing later).
- [x] #5
- [x] Consider [Comlink](https://github.com/GoogleChromeLabs/comlink/tree/main) for web worker communication (if workers are needed)
- [x] Add thorough documentation on technical decisions: https://github.com/penumbra-zone/web/pull/13

At the end of this sprint, we should re-evaluate if this should be continue as a parallel workstream or start having zpoken oriented toward migration to this repo.
