### ISSUE TITLE
Tracking Issue: Staking

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#463]
Support in mini-front the ability to view validators and stake penumbra with them

- [ ] Add new `Staking` tab 
- [ ] Query: List of all validators in network (fields: voting power, share, commission, state, bonding state, validator info)
- [ ] View: user's current delegations (unbonded, bonded)
- [ ] Tx: 
  - [ ] Delegate to a validator
  - [ ] Undelegate from validator (show unbonding status)
  - [ ] Undelegate claim (after unbonding)

**Comment by hdevalence** [comment]
xref https://github.com/penumbra-zone/web/pull/569#issuecomment-1957738474

**Comment by hdevalence** [comment]
#540 and #541 should not be separate issues, since the staking information to display is token-based.
