### ISSUE TITLE
Tracking issue: Deploy new dapp+extension

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#49]
The minimum remaining features to complete until we can:
1. Deploy dapp to [app.testnet.penumbra.zone](https://app.testnet.penumbra.zone/)
2. Deploy extension to [chrome web store](https://chromewebstore.google.com/detail/penumbra-wallet/lkpmkhpnhknhmibgnmmhdhgdilepfghe)

- [x] https://github.com/penumbra-zone/web/pull/38
- [x] #50
- [x] #55
- [x] #51 
- [x] #53
- [x] https://github.com/penumbra-zone/web/issues/59
- [x] #52
- [x] https://github.com/penumbra-zone/web/issues/62
- [x] https://github.com/penumbra-zone/web/pull/48
- [x] https://github.com/penumbra-zone/web/issues/67
- [x] #65
- [x] BIP44 is merged to testnet
- [x] #54
- [x] Deprecate/archive old repos:
  - [x] https://github.com/penumbra-zone/penumbra_dapp
  - [x] https://github.com/penumbra-zone/wallet

**Comment by conorsch** [comment]
The Firebase hosting in #48 is looking good. Once that PR is merged, I'll try a few manual deploys via the web UI and confirm it works reliably. We don't yet have secrets in place in this repo for Firebase access; I'll wire that up in the meantime while we wait for 48 to land.

**Comment by conorsch** [comment]
> The Firebase hosting in https://github.com/penumbra-zone/web/pull/48 is looking good. Once that PR is merged, I'll try a few manual deploys via the web UI and confirm it works reliably.

We followed up with https://github.com/penumbra-zone/web/pull/78 and now the action is passing: https://github.com/penumbra-zone/web/actions/runs/6408559513
