### ISSUE TITLE
Tracking Issue: New pricing method

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#530]
Protos now contain equivalent pricing numeraires for value views. Support this in our extension rpc balances method as well as the frontend UI

- [x] https://github.com/penumbra-zone/web/issues/526
- [x] https://github.com/penumbra-zone/web/issues/525
- [x] https://github.com/penumbra-zone/penumbra/issues/3838
- [x] #556
- [x] #557
- [x] https://github.com/penumbra-zone/web/issues/527
- [x] https://github.com/penumbra-zone/web/issues/794
- [x] https://github.com/penumbra-zone/web/issues/529
