### ISSUE TITLE
Add prices table to IndexedDB

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#556]
Replaces #526, in light of https://github.com/penumbra-zone/penumbra/issues/3838

I think the following columns would be sufficient:

- `priced_asset: AssetId`: the asset being priced
- `numeraire: AssetId`: the numeraire measuring the price
- `numeraire_per_unit: f64`: the amount of the numeraire per unit of the priced asset
- `expiry_height: u64`: the block height at which time the price is considered "stale" and no longer valid

Then a query to generate a `TransactionPerspective.Price` for a `priced_asset`, `numeraire` pair can (1) check for the pair in the table and (2) check that `expiry_height < sync_height`, and we never have to clean up stale prices.

This also lets us naturally handle different cases as in the original #526 and in #527 and in #528:

- [ ] For #526, we have a config setting (not necessarily user-exposed, just config data for now) for the preferred numeraire `N`. When we scan a block, we look for trades of asset `X` into `N`, and use the trade info to write into the prices table with an expiry height some (relatively short) number of blocks ahead, say 200 (~= 16 minutes).
- [ ] For #527, as we sync across an epoch boundary (probably we want to skip this while catching up), we can fetch the validator set using the [`ValidatorInfo`](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.core.component.stake.v1#penumbra.core.component.stake.v1.QueryService.ValidatorInfo) request, compute prices of delegation tokens in terms of the staking token, and write those "chain-native" prices in with an expiry height set to the max epoch length
- [ ] For #528, (which we don't need to do until implementing LP support for web), we can have some other configurable polling interval to check on the state of the user's positions and use that as the expiry height.
