### ISSUE TITLE
Tracking issue: wasm crate tests

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#691]
We can't test wasm functions that use indexed-db global using vi.test so we have to write tests on rust with indexed-db mock

- [x] https://github.com/penumbra-zone/web/issues/1830
- [x] https://github.com/penumbra-zone/web/issues/1831
- [ ] https://github.com/penumbra-zone/web/issues/1832
- [ ] https://github.com/penumbra-zone/web/issues/1833
- [ ] #694
- [ ] https://github.com/penumbra-zone/web/issues/1835
- [ ] https://github.com/penumbra-zone/web/issues/1836
- [ ] https://github.com/penumbra-zone/web/issues/1837
- [ ] https://github.com/penumbra-zone/web/issues/1838
- [ ] https://github.com/penumbra-zone/web/issues/1839
- [ ] https://github.com/penumbra-zone/web/issues/1840
- [ ] https://github.com/penumbra-zone/web/issues/1841
- [ ] https://github.com/penumbra-zone/web/issues/1842
- [ ] https://github.com/penumbra-zone/web/issues/1843
- [ ] https://github.com/penumbra-zone/web/issues/1844
- [ ] https://github.com/penumbra-zone/web/issues/1845
- [ ] https://github.com/penumbra-zone/web/issues/1846

**Comment by TalDerei** [comment]
@grod220 perhaps we should prioritize our efforts on expanding test coverage for our wasm package in the near term?
