### ISSUE TITLE
Tracking issue: NPM publishing

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#729]
- [x] https://github.com/penumbra-zone/web/issues/718
- [x] https://github.com/penumbra-zone/web/pull/672
- [x] https://github.com/penumbra-zone/web/issues/750
- [x] https://github.com/penumbra-zone/web/issues/724
- [x] #893
- [x] #892
- [x] https://github.com/penumbra-zone/web/issues/676
- [x] https://github.com/penumbra-zone/web/issues/684
- [x] https://github.com/penumbra-zone/web/issues/737
- [x] #894
- [x] https://github.com/penumbra-zone/web/issues/733
- [x] #741
- [x] https://github.com/penumbra-zone/web/issues/730
- [x] https://github.com/penumbra-zone/web/issues/738
- [x] https://github.com/penumbra-zone/web/issues/731
- [x] https://github.com/penumbra-zone/web/issues/728
- [x] https://github.com/penumbra-zone/web/issues/736
- [x] #680 
- [x] https://github.com/penumbra-zone/web/issues/749
- [x] https://github.com/penumbra-zone/web/issues/762

**Comment by turbocrime** [comment]
https://github.com/penumbra-zone/web/issues/722 may be relevant if we don't bundle when publishing.

currently tsconfigs all extend a parent config in another package. this won't be included in pack, so tsconfig in the package will just break

**Comment by TalDerei** [comment]
what's the current status of our NPM publishing workflow?

**Comment by TalDerei** [comment]
closing as complete
