### ISSUE TITLE
Tracking issue: Audit Action Views

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#875]
Previously we were defaulting to showing no data for opaque action views. https://github.com/penumbra-zone/web/pull/874 makes it more clear we haven't implemented it yet. This tracking issue's purpose is to ensure we are displaying the correct fields for both visible and opaque action views.

Important files:
- Action view [proto definition](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.core.transaction.v1#penumbra.core.transaction.v1.ActionView)
- Tx Approval [perspective translation](https://github.com/penumbra-zone/web/blob/f2cf25868246804749bc3298ae553f78122a6076/packages/perspective/translators/action-view.ts#L7-L31)
- Action view [component](https://github.com/penumbra-zone/web/blob/f2cf25868246804749bc3298ae553f78122a6076/packages/ui/components/ui/tx/view/action-view.tsx#L44-L115)

**Task**: 
- Go through each view, enumerating the fields of both opaque and visible cases that are critical to display.
- Make PRs that add these fields to our action views
- Create human readable spec in markdown representing the fields displayed and not with reasoning.

### Views to audit

- [x] SpendView
- [x] OutputView
- [x] SwapView
- [x] SwapClaimView
- [x] Delegate
- [x] Undelegate
- [x] UndelegateClaim
- [x] ActionDutchAuctionSchedule
- [x] ActionDutchAuctionEnd
- [x] ActionDutchAuctionWithdrawView
- [x] Ics20Withdrawal
----------------------------------------------------------------
### Related tasks
- [x] https://github.com/penumbra-zone/web/issues/889
- [x] https://github.com/penumbra-zone/web/issues/1039
- [x] https://github.com/penumbra-zone/web/issues/1040
- [x] https://github.com/penumbra-zone/web/issues/1065
- [x] https://github.com/penumbra-zone/web/issues/1135

**Comment by TalDerei** [comment]
Flagging that during the core backlog refinement meeting today, Henry flagged this as an important action-item.
