### ISSUE TITLE
Tracking issue: Dutch auction support in the web 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#942]
Support the ability to perform Gradual Dutch Actions (GDAs). References https://github.com/penumbra-zone/penumbra/issues/4196

- [x] #944
- [x] https://github.com/penumbra-zone/web/issues/978
- [x] #1018
- [x] #1019 
- [x] #1032
- [x] #943
- [x] #980
- [x] #1020
- [x] #1059
- [x] https://github.com/penumbra-zone/web/issues/981
- [x] #1081
- [x] #1088
- [x] #1155
- [x] #1146
- [x] #1157
- [x] https://github.com/penumbra-zone/web/issues/1181
- [x] #1156
- [x] #1198
- [x] #1284
- [x] #1277
- [x] #1285
- [x] #1090
- [x] https://github.com/penumbra-zone/web/issues/1212
- [x] #1166

**Comment by TalDerei** [comment]
currently blocked until **pcli M0** in dependency graph is complete.
