### ISSUE TITLE
Tracking issue: web milestone

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#97]
Given the progress with the new web app + extension, this tracking issue defines a milestone for communicating this work to users. Ideally, it's not terribly long after v0.63 goes live. Requirements:

- [ ] #49
- [ ] #69
- [ ] Balances can be viewed on dapp
- [ ] Transactions can be viewed on dapp
- [ ] User can send funds (tx building+broacast)
- [ ] Page to view single transaction in depth
- [ ] Education panels in dapp need content
- [ ] Gray out not-ready features 
- [ ] v0.63 extension is published
- [ ] Blogpost on penumbra.zone written & communicated
